config/routes.rb
Rails.application.routes.draw do

  root 'channels#index'

  resources :channels
  resources :streams

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :streams
  scope :active, -> { where(deleted: false)}
  validates :name, presence: true

  def next
    n = Channel.active.where("id > ?", id).first
    return Channel.first if n.nil?
    return n
  end

  def live_streams
    self.streams.where(:live => true)
  end

  def prev
    Channel.active.where("id < ?", id).first
  end

  def mark_as_deleted
    self.deleted = true
    self.save
  end

# Schema
# - id
# - name
# - streams
# - deleted

end

app/models/stream.rb
class Stream < ActiveRecord::Base
  validates :url, presence: true
  validates :source, presence: true

  belongs_to :channel

#   Schema
#   - id
#   - url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController


  def list
  end

  def show
    @channel = Channel.where(:id => params[:id]).first
    @channels = Channel.active # get all channels for showing in the list
    # get first live stream for that channel, and prefer m3u8 over embed
    streams = @channel.live_streams
    m3u8_stream = streams.where(:source => 'm3u8').first
    embed_stream = streams.where(:source => 'embed').first
    @stream = m3u8_stream.nil? ? embed_stream : m3u8_stream
    # redirect to channels if channel is deleted
    flash[:warn] = "Channel is deleted" if @channel.nil? || @channel.deleted
    redirect_to '/channels' if @channel.nil? || @channel.deleted
  end

  def index
    @channels = Channel.active.all
  end

  def update
    params.permit!
    @channel = Channel.find(params[:id])
    @channel.update(params[:channel])
    flash[:success] = 'Updated successful'
    redirect_to action: 'edit', id: @channel.id
  end

  def create
    params.permit!
    @channel = Channel.new(params[:channel])
    if @channel.save
      flash[:success] = "Channel saved with name: #{@channel.name}"
      redirect_to action: 'index'
    else
      flash[:warn] = "Channel did not save! :("
      redirect_to action: 'index'
    end
  end

  def destroy
    params.permit!
    @channel = Channel.find(params[:id])
    @channel.mark_as_deleted
    flash[:success] = "Deleted channel #{@channel.name}"
    redirect_to action: 'index'
  end


  def edit
    @channel = Channel.find(params[:id])
  end

end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController


  def update
    params.permit!
    @stream = Stream.find(params[:id])
    @stream.update(params[:stream])
    flash[:success] = 'Update successful'
    redirect_to controller: 'channels', action: 'edit'
  end

  def create
    params.permit!
    @channel = Channel.find(params[:channel_id])
    @stream = @channel.streams.new(params[:stream])
    @stream.live = true
    if @stream.save
      flash[:success] = "Stream saved"
      redirect_to controller: 'channels', action: 'edit', id: @stream.channel_id
    else
      flash[:warn] = "Stream did not save"
      redirect_to controller: 'channels', action: 'edit', id: @stream.channel_id
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/channels/_channel_list.html.erb
<div class="list-group channel-list-group">
  <% @channels.each do |channel| %>
      <%= link_to channel.name,
                  {:action => 'show', :id => channel.id },
                  html_options = {:class => 'list-group-item channel-list-item', :onclick => 'return cleanUp();' } %>
  <% end %>
</div>

app/views/channels/_embed.html.erb
<div class="embed-responsive-16by9">
  <iframe class="embed-responsive-item" width="100%" height="600px"
          src="<%= @stream.url %>" scrolling="0" frameborder="0" allowfullscreen="1">
  </iframe>
</div>

app/views/channels/_m3u8.html.erb
<video id="player" width=960 height=540 class="video-js vjs-default-skin"
       controls preload="auto" data-setup="{}">
  <source src="<%= @stream.url %>" type="application/x-mpegURL">
</video>

<script>
  var player = videojs('player');
  player.play();
</script>

app/views/channels/edit.html.erb
<div>
  Editing Channel
  <%= @channel.name %>

  <%= form_for @channel, url: {action: 'update'}, html: {class: "form-inline"} do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, :placeholder => @channel.name, class: 'form-control' %>
        <%= f.submit "Save", :class => 'btn btn-default'%>
      </div>
  <% end %>

  <p>Streams</p>

  <%= form_for @channel.streams.new, url: {controller: 'streams',action: 'create', channel_id: @channel.id}, html: {class: "form-inline"} do |f| %>
      <li>
        <div class="form-group">
          <label>URL:</label>
          <%= f.text_field :url, :placeholder => 'http://example.com', class: 'form-control' %>
          <label>Source:</label>
          <%= f.text_field :source, :placeholder => 'embed or m3u8', class: 'form-control' %>
          <%= f.submit "Save", :class => 'btn btn-default'%>
        </div>
      </li>
  <% end %>


  <ol>
  <% @channel.streams.where("id is not null").each do |stream| %>
    <p>
      <%= form_for stream, url: {controller: 'streams',action: 'update'}, html: {class: "form-inline"} do |f| %>
        <li>
          <div class="form-group">
            <label>ID:</label>
            <%= stream.id %>
          <label>URL:</label>
          <%= f.text_field :url, :placeholder => stream.url, class: 'form-control' %>
          <label>Source:</label>
          <%= f.text_field :source, :placeholder => stream.source, class: 'form-control' %>
          <%= f.submit "Save", :class => 'btn btn-default'%>
        </div>
        </li>
      <% end %>
    </p>
  <% end %>
  </ol>




</div>

app/views/channels/index.html.erb
<div class="row homepage_title">
  <h1>Welcome to Telesio</h1>
</div>

<b>
  <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
  <% end -%>
</b>


<div class="row">
  <div class="col-md-12">
    <%= form_for Channel.new, url: {action: "create"}, html: {class: "form-inline"} do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, :placeholder => 'Channel Name' %>
          <%= f.submit "Save", :class => 'btn btn-default'%>
        </div>
    <% end %>
  </div>
</div>

<div class="row">
  <ul>
    <% @channels.each do |c| %>
        <li>
          <%= c.id %>:
          <% if c.streams.count > 0 %>
            <%= link_to "#{c.name}", channel_path(c) %>
          <% else %>
            <%= c.name %>
          <% end %>
          => Live =>
          <% c.streams.each do |stream| %>
              <%= stream.live %>
          <% end %>
          <%= link_to 'Delete', c, method: :delete, data: {confirm: "Are you sure?"} %>
          /
          <%= link_to 'Edit', controller: 'channels', action: 'edit', id: c %>
        </li>
    <% end %>
  </ul>
</div>

app/views/channels/show.html.erb
<div class="row channelview">
  <div class="col-md-10">

    <% if @stream.source == 'embed' %>
        <%= render 'embed' %>
    <% else %>
        <%= render 'm3u8' %>
    <% end %>

  </div>

  <div class="col-md-2">
    <p id="current_channel">Showing <%= @channel.name %></p>
    <p><%= link_to "Next channel", {:action => 'show', :id => @channel.next.id },
                   html_options = {:onclick => 'return cleanUp();', :id => 'nextChannel'} %></p>
    <%= render 'channel_list' %>
  </div>
</div>

<script>
  function cleanUp() {
    var m3u8Player = $('#player').length;
    if (m3u8Player > 0) {
      var player = videojs('player');
      player.dispose();
    }
  }

  key('right', nextChannel);
  key('enter', fullScreen);
  key('up', volumeUp);
  key('down', volumeDown);

  function nextChannel() {
    var currChannel = $('#nextChannel')[0];
    window.location.href = currChannel.href;
  }

  function fullScreen() {
    player.requestFullscreen();
  }

  function volumeUp() {
    var vol = player.volume();
    var newVol = vol + 0.5;
    player.volume(newVol);
  }

  function volumeDown() {
    var vol = player.volume();
    var newVol = vol - 0.5;
    player.volume(newVol);
  }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telesio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

</html>